spring:
  application:
    name: MONGODB
  data:
    mongodb:
      host: localhost
      port: 27018
      database: storingDB
      username: test
      password: test
      authentication-database: admin
      uri: mongodb://test:test@localhost:27018/
  kafka:
    bootstrap-servers: localhost:9092
  rabbitmq:
    host: localhost
    virtual-host: vhost
    username: test
    password: test

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
    instance:
      preferIpAddress: true

server:
  servlet:
    context-path: /api
  port: 8086